-- Скрипт сгенерирован инструментом ERD в pgAdmin 4.
-- При обнаружении ошибки создайте issue с описанием воспроизведения: https://github.com/pgadmin-org/pgadmin4/issues/new/choose
BEGIN;

CREATE SCHEMA IF NOT EXISTS trans;

COMMENT ON SCHEMA trans
    IS 'Книги, исходные сегменты, переводы и точки вставки';

CREATE TABLE IF NOT EXISTS trans.book
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title character varying(128) COLLATE pg_catalog."default" NOT NULL,
    original_language character varying(3) COLLATE pg_catalog."default" NOT NULL,
    path character varying COLLATE pg_catalog."default",
    translated_path character varying COLLATE pg_catalog."default",
    translated_element_path character varying COLLATE pg_catalog."default",
    CONSTRAINT book_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN trans.book.original_language
    IS 'Трёхсимвольный код языка оригинала книги';

COMMENT ON COLUMN trans.book.path
    IS 'S3-путь к оригинальному PDF-документу';

COMMENT ON COLUMN trans.book.translated_path
    IS 'S3-путь к переведённому PDF-документу';

COMMENT ON COLUMN trans.book.translated_element_path
    IS 'S3-путь к переведённому элементу книги';

CREATE TABLE IF NOT EXISTS trans.insertion
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    path text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT insertion_pkey PRIMARY KEY (id),
    CONSTRAINT insertion_path_key UNIQUE (path)
);

CREATE TABLE IF NOT EXISTS trans.segment
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    book_id bigint NOT NULL,
    stable_key character varying(64) COLLATE pg_catalog."default" NOT NULL,
    insertion_id bigint,
    text_segment_hash text COLLATE pg_catalog."default",
    sequential_number integer NOT NULL,
    CONSTRAINT segment_pkey PRIMARY KEY (id),
    CONSTRAINT uq_segment_book_sequence UNIQUE (book_id, sequential_number),
    CONSTRAINT uq_segment_book_stable_key UNIQUE (book_id, stable_key)
);

COMMENT ON COLUMN trans.segment.stable_key
    IS 'Стабильный ключ позиции в оригинальном документе';

COMMENT ON COLUMN trans.segment.insertion_id
    IS 'Ссылка на вставку, связанную с сегментом';

COMMENT ON COLUMN trans.segment.text_segment_hash
    IS 'Ссылка на текст, связанный с сегментом';

COMMENT ON COLUMN trans.segment.sequential_number
    IS 'Порядковый номер сегмента внутри книги, начиная с единицы';

CREATE TABLE IF NOT EXISTS trans.text_segment
(
    text_hash text COLLATE pg_catalog."default" NOT NULL,
    text text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT text_segment_pkey PRIMARY KEY (text_hash)
);

COMMENT ON COLUMN trans.text_segment.text_hash
    IS 'Хеш исходного текста, рассчитанный приложением';

CREATE TABLE IF NOT EXISTS trans.translated_segment
(
    original_text_hash text COLLATE pg_catalog."default" NOT NULL,
    language character varying(32) COLLATE pg_catalog."default" NOT NULL,
    translation text COLLATE pg_catalog."default" NOT NULL,
    evaluation smallint,
    retries integer NOT NULL DEFAULT 0,
    CONSTRAINT pk_translated_segment PRIMARY KEY (original_text_hash, language)
);

COMMENT ON COLUMN trans.translated_segment.evaluation
    IS 'Оценка качества перевода от 1 до 5';

ALTER TABLE IF EXISTS trans.segment
    ADD CONSTRAINT fk_segment_book FOREIGN KEY (book_id)
    REFERENCES trans.book (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS trans.segment
    ADD CONSTRAINT fk_segment_insertion FOREIGN KEY (insertion_id)
    REFERENCES trans.insertion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_segment_insertion_id
    ON trans.segment(insertion_id);


ALTER TABLE IF EXISTS trans.segment
    ADD CONSTRAINT fk_segment_text_segment FOREIGN KEY (text_segment_hash)
    REFERENCES trans.text_segment (text_hash) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_segment_text_segment_hash
    ON trans.segment(text_segment_hash);


ALTER TABLE IF EXISTS trans.translated_segment
    ADD CONSTRAINT fk_translated_segment_original_text FOREIGN KEY (original_text_hash)
    REFERENCES trans.text_segment (text_hash) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_translated_segment_language
    ON trans.translated_segment(language);

END;
