--liquibase formatted sql

--changeset copybarca:001-cumulative-trans-schema splitStatements:true endDelimiter:;
CREATE SCHEMA IF NOT EXISTS trans;

CREATE TABLE IF NOT EXISTS trans.book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(128) NOT NULL,
    original_language VARCHAR(3) NOT NULL,
    path VARCHAR,
    translated_path VARCHAR,
    translated_element_path VARCHAR,
    CONSTRAINT book_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS trans.insertion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    path TEXT NOT NULL,
    CONSTRAINT insertion_pkey PRIMARY KEY (id),
    CONSTRAINT insertion_path_key UNIQUE (path)
);

CREATE TABLE IF NOT EXISTS trans.text_segment (
    text_hash TEXT NOT NULL,
    text TEXT NOT NULL,
    CONSTRAINT text_segment_pkey PRIMARY KEY (text_hash)
);

CREATE TABLE IF NOT EXISTS trans.segment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    book_id BIGINT NOT NULL,
    stable_key VARCHAR(64) NOT NULL,
    insertion_id BIGINT,
    text_segment_hash TEXT,
    sequential_number INTEGER NOT NULL,
    CONSTRAINT segment_pkey PRIMARY KEY (id),
    CONSTRAINT uq_segment_book_sequence UNIQUE (book_id, sequential_number),
    CONSTRAINT uq_segment_book_stable_key UNIQUE (book_id, stable_key),
    CONSTRAINT fk_segment_book
        FOREIGN KEY (book_id) REFERENCES trans.book (id) ON DELETE CASCADE,
    CONSTRAINT fk_segment_insertion
        FOREIGN KEY (insertion_id) REFERENCES trans.insertion (id) ON DELETE SET NULL,
    CONSTRAINT fk_segment_text_segment
        FOREIGN KEY (text_segment_hash) REFERENCES trans.text_segment (text_hash) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS trans.translated_segment (
    original_text_hash TEXT NOT NULL,
    language VARCHAR(32) NOT NULL,
    translation TEXT NOT NULL,
    evaluation SMALLINT,
    retries INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT pk_translated_segment PRIMARY KEY (original_text_hash, language),
    CONSTRAINT fk_translated_segment_original_text
        FOREIGN KEY (original_text_hash) REFERENCES trans.text_segment (text_hash) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_segment_insertion_id
    ON trans.segment (insertion_id);

CREATE INDEX IF NOT EXISTS idx_segment_text_segment_hash
    ON trans.segment (text_segment_hash);

CREATE INDEX IF NOT EXISTS idx_translated_segment_language
    ON trans.translated_segment (language);

COMMENT ON SCHEMA trans IS 'Книги, исходные сегменты, переводы и точки вставки';
COMMENT ON COLUMN trans.book.original_language IS 'Трёхсимвольный код языка оригинала книги';
COMMENT ON COLUMN trans.book.path IS 'S3-путь к оригинальному PDF-документу';
COMMENT ON COLUMN trans.book.translated_path IS 'S3-путь к переведённому PDF-документу';
COMMENT ON COLUMN trans.book.translated_element_path IS 'S3-путь к переведённому элементу книги';
COMMENT ON COLUMN trans.text_segment.text_hash IS 'Хеш исходного текста, рассчитанный приложением';
COMMENT ON COLUMN trans.segment.stable_key IS 'Стабильный ключ позиции в оригинальном документе';
COMMENT ON COLUMN trans.segment.insertion_id IS 'Ссылка на вставку, связанную с сегментом';
COMMENT ON COLUMN trans.segment.text_segment_hash IS 'Ссылка на текст, связанный с сегментом';
COMMENT ON COLUMN trans.segment.sequential_number IS 'Порядковый номер сегмента внутри книги, начиная с единицы';
COMMENT ON COLUMN trans.translated_segment.evaluation IS 'Оценка качества перевода от 1 до 5';

--rollback DROP SCHEMA IF EXISTS trans CASCADE;
