--liquibase formatted sql

--changeset copybarca:001-cumulative-trans-schema splitStatements:true endDelimiter:;
CREATE SCHEMA IF NOT EXISTS trans;

CREATE TABLE IF NOT EXISTS trans.book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(128) NOT NULL,
    original_language VARCHAR(3) NOT NULL,
    path VARCHAR,
    translated_path VARCHAR,
    translated_element_path VARCHAR,
    CONSTRAINT book_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS trans.insertion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    path TEXT NOT NULL,
    CONSTRAINT insertion_pkey PRIMARY KEY (id),
    CONSTRAINT insertion_path_key UNIQUE (path)
);

CREATE TABLE IF NOT EXISTS trans.text_segment (
    text_hash TEXT NOT NULL,
    text TEXT NOT NULL,
    CONSTRAINT text_segment_pkey PRIMARY KEY (text_hash)
);

CREATE TABLE IF NOT EXISTS trans.segment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    book_id BIGINT NOT NULL,
    stable_key VARCHAR(64) NOT NULL,
    insertion_id BIGINT,
    text_segment_hash TEXT,
    sequential_number INTEGER NOT NULL,
    CONSTRAINT segment_pkey PRIMARY KEY (id),
    CONSTRAINT uq_segment_book_sequence UNIQUE (book_id, sequential_number),
    CONSTRAINT uq_segment_book_stable_key UNIQUE (book_id, stable_key),
    CONSTRAINT fk_segment_book
        FOREIGN KEY (book_id) REFERENCES trans.book (id) ON DELETE CASCADE,
    CONSTRAINT fk_segment_insertion
        FOREIGN KEY (insertion_id) REFERENCES trans.insertion (id) ON DELETE SET NULL,
    CONSTRAINT fk_segment_text_segment
        FOREIGN KEY (text_segment_hash) REFERENCES trans.text_segment (text_hash) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS trans.translated_segment (
    original_text_hash TEXT NOT NULL,
    language VARCHAR(32) NOT NULL,
    translation TEXT NOT NULL,
    evaluation SMALLINT,
    retries INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT pk_translated_segment PRIMARY KEY (original_text_hash, language),
    CONSTRAINT fk_translated_segment_original_text
        FOREIGN KEY (original_text_hash) REFERENCES trans.text_segment (text_hash) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_segment_insertion_id
    ON trans.segment (insertion_id);

CREATE INDEX IF NOT EXISTS idx_segment_text_segment_hash
    ON trans.segment (text_segment_hash);

CREATE INDEX IF NOT EXISTS idx_translated_segment_language
    ON trans.translated_segment (language);

COMMENT ON SCHEMA trans IS 'Книги, исходные сегменты, переводы и точки вставки';
COMMENT ON COLUMN trans.book.original_language IS 'Трёхсимвольный код языка оригинала книги';
COMMENT ON COLUMN trans.book.path IS 'S3-путь к оригинальному PDF-документу';
COMMENT ON COLUMN trans.book.translated_path IS 'S3-путь к переведённому PDF-документу';
COMMENT ON COLUMN trans.book.translated_element_path IS 'S3-путь к переведённому элементу книги';
COMMENT ON COLUMN trans.text_segment.text_hash IS 'Хеш исходного текста, рассчитанный приложением';
COMMENT ON COLUMN trans.segment.stable_key IS 'Стабильный ключ позиции в оригинальном документе';
COMMENT ON COLUMN trans.segment.insertion_id IS 'Ссылка на вставку, связанную с сегментом';
COMMENT ON COLUMN trans.segment.text_segment_hash IS 'Ссылка на текст, связанный с сегментом';
COMMENT ON COLUMN trans.segment.sequential_number IS 'Порядковый номер сегмента внутри книги, начиная с единицы';
COMMENT ON COLUMN trans.translated_segment.evaluation IS 'Оценка качества перевода от 1 до 5';

--rollback DROP SCHEMA IF EXISTS trans CASCADE;


--changeset copybarca:002-pipeline-processes-and-extraction splitStatements:true endDelimiter:;
CREATE SCHEMA IF NOT EXISTS "scheduled-processes";

ALTER TABLE trans.segment
    ADD COLUMN IF NOT EXISTS physical_page INTEGER,
    ADD COLUMN IF NOT EXISTS bbox_json TEXT,
    ADD COLUMN IF NOT EXISTS style VARCHAR(32),
    ADD COLUMN IF NOT EXISTS translatable BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE trans.insertion
    ADD COLUMN IF NOT EXISTS media_type VARCHAR(64),
    ADD COLUMN IF NOT EXISTS checksum VARCHAR(80);

CREATE TABLE IF NOT EXISTS trans.insertion_text_region (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    insertion_id BIGINT NOT NULL,
    stable_key VARCHAR(64) NOT NULL,
    original_text_hash TEXT NOT NULL,
    sequential_number INTEGER NOT NULL,
    pixel_bbox_json TEXT NOT NULL,
    ocr_confidence NUMERIC(5, 2),
    CONSTRAINT insertion_text_region_pkey PRIMARY KEY (id),
    CONSTRAINT fk_insertion_text_region_insertion
        FOREIGN KEY (insertion_id) REFERENCES trans.insertion (id) ON DELETE CASCADE,
    CONSTRAINT fk_insertion_text_region_text
        FOREIGN KEY (original_text_hash) REFERENCES trans.text_segment (text_hash)
        ON DELETE RESTRICT,
    CONSTRAINT uq_insertion_text_region_stable_key UNIQUE (stable_key),
    CONSTRAINT uq_insertion_text_region_order
        UNIQUE (insertion_id, sequential_number)
);

CREATE TABLE IF NOT EXISTS "scheduled-processes".pdf_extraction_process (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    book_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL,
    pdf_sha256 VARCHAR(80),
    extractor_version VARCHAR(64),
    expected_segment_count INTEGER,
    expected_image_count INTEGER,
    expected_region_count INTEGER,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT pdf_extraction_process_pkey PRIMARY KEY (id),
    CONSTRAINT fk_pdf_extraction_book
        FOREIGN KEY (book_id) REFERENCES trans.book (id) ON DELETE CASCADE,
    CONSTRAINT chk_pdf_extraction_status
        CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT uq_pdf_extraction_book UNIQUE (book_id)
);

CREATE TABLE IF NOT EXISTS "scheduled-processes".translation_process (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    book_id BIGINT NOT NULL,
    target_language VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT translation_process_pkey PRIMARY KEY (id),
    CONSTRAINT fk_translation_process_book
        FOREIGN KEY (book_id) REFERENCES trans.book (id) ON DELETE CASCADE,
    CONSTRAINT chk_translation_process_status
        CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT uq_translation_process_book_language
        UNIQUE (book_id, target_language)
);

CREATE TABLE IF NOT EXISTS "scheduled-processes".pdf_build_process (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    book_id BIGINT NOT NULL,
    target_language VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT pdf_build_process_pkey PRIMARY KEY (id),
    CONSTRAINT fk_pdf_build_book
        FOREIGN KEY (book_id) REFERENCES trans.book (id) ON DELETE CASCADE,
    CONSTRAINT chk_pdf_build_status
        CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT uq_pdf_build_book_language
        UNIQUE (book_id, target_language)
);

CREATE INDEX IF NOT EXISTS idx_insertion_text_region_insertion
    ON trans.insertion_text_region (insertion_id);
CREATE INDEX IF NOT EXISTS idx_insertion_text_region_source_hash
    ON trans.insertion_text_region (original_text_hash);

--rollback DROP TABLE IF EXISTS "scheduled-processes".pdf_build_process;
--rollback DROP TABLE IF EXISTS "scheduled-processes".translation_process;
--rollback DROP TABLE IF EXISTS "scheduled-processes".pdf_extraction_process;
--rollback DROP TABLE IF EXISTS trans.insertion_text_region;
